survos_tabler:
  routes:
    login: app_login
    logout: app_logout
    home: app_homepage
    register: app_register
  options:
    # consider https://startbootstrap.com/previews/simple-sidebar as another theme
    theme: tabler
    layout: horizontal
#    allow_login: true
  app:
      social:
        facebook: https://facebook.com/kidpanalley
      code: kpa
      abbr: <b>kpa</b>Archive

  favicon:
    text: KP

  menu_options:
    frontPage: false
    showAppMenu: true
