<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * @return array<string, array{    // Import name as key, description of the imported file as value
 *     path: string,               // Logical, relative or absolute path to the file
 *     type?: 'js'|'css'|'json',   // Type of the file, defaults to 'js'
 *     entrypoint?: bool,          // Whether the file is an entrypoint, for 'js' only
 * }|array{
 *     version: string,            // Version of the remote package
 *     package_specifier?: string, // Remote "package-name/path" specifier, defaults to the import name
 *     type?: 'js'|'css'|'json',
 *     entrypoint?: bool,
 * }>
 */
return [
    'app' => ['path' => './assets/app.js', 'entrypoint' => true],
    'admin' => ['path' => './assets/admin.js', 'entrypoint' => true],
    'meili' => ['path' => './assets/meili.js', 'entrypoint' => true],
    '@symfony/stimulus-bundle' => ['path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js'],
    'axios' => ['version' => '1.7.9'],
    'datatables.net-plugins/i18n/en-GB.mjs' => ['version' => '3.1.2'],
    'datatables.net-bs5' => ['version' => '3.1.3'],
    'jquery' => ['version' => '4.0.0'],
    'datatables.net' => ['version' => '3.1.3'],
    'datatables.net-bs5/css/dataTables.bootstrap5.css' => ['version' => '3.1.3', 'type' => 'css'],
    'datatables.net-buttons-bs5' => ['version' => '4.1.2'],
    'datatables.net-buttons' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-responsive-bs5' => ['version' => '4.1.1'],
    'datatables.net-responsive' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-scroller-bs5' => ['version' => '3.0.0'],
    'datatables.net-scroller' => ['version' => '3.0.0'],
    'datatables.net-scroller-bs5/css/scroller.bootstrap5.css' => ['version' => '3.0.0', 'type' => 'css'],
    'datatables.net-searchpanes-bs5' => ['version' => '2.3.5'],
    'datatables.net-searchpanes' => ['version' => '2.3.5'],
    'datatables.net-searchpanes-bs5/css/searchPanes.bootstrap5.css' => ['version' => '2.3.5', 'type' => 'css'],
    'datatables.net-select-bs5' => ['version' => '4.1.1'],
    'datatables.net-select' => ['version' => '4.1.1'],
    'datatables.net-select-bs5/css/select.bootstrap5.css' => ['version' => '4.1.1', 'type' => 'css'],
    '@hotwired/stimulus' => ['version' => '3.2.2'],
    '@popperjs/core' => ['version' => '2.11.8'],
    'bootstrap/dist/css/bootstrap.min.css' => ['version' => '5.3.8', 'type' => 'css'],
    'stimulus-content-loader' => ['version' => '4.2.0'],
    'stimulus-reveal-controller' => ['version' => '4.1.0'],
    '@kanety/stimulus-zoom-image' => ['version' => '1.1.0'],
    '@kanety/stimulus-static-actions' => ['version' => '1.1.0'],
    'perfect-scrollbar' => ['version' => '1.5.6'],
    'perfect-scrollbar/css/perfect-scrollbar.min.css' => ['version' => '1.5.6', 'type' => 'css'],
    'bootstrap-icons/font/bootstrap-icons.min.css' => ['version' => '1.11.3', 'type' => 'css'],
    'idb' => ['version' => '8.0.1'],
    'js-logger' => ['version' => '1.6.1'],
    'datatables.net-searchbuilder-bs5' => ['version' => '2.1.1'],
    'datatables.net-searchbuilder' => ['version' => '2.1.1'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.css' => ['version' => '2.1.1', 'type' => 'css'],
    '@kurkle/color' => ['version' => '0.3.4'],
    'datatables.net-plugins/i18n/es-ES.mjs' => ['version' => '3.1.2'],
    'datatables.net-plugins/i18n/de-DE.mjs' => ['version' => '3.1.2'],
    '@tabler/core/dist/css/tabler.min.css' => ['version' => '1.6.1', 'type' => 'css'],
    'escape-html' => ['version' => '1.0.3'],
    'flag-icons' => ['version' => '7.5.0'],
    'flag-icons/css/flag-icons.min.css' => ['version' => '7.5.0', 'type' => 'css'],
    '@algolia/events' => ['version' => '4.0.1'],
    'hogan.js' => ['version' => '3.0.2'],
    'htm/preact' => ['version' => '3.1.1'],
    '@babel/runtime/helpers/extends' => ['version' => '7.28.4'],
    '@babel/runtime/helpers/defineProperty' => ['version' => '7.28.4'],
    '@babel/runtime/helpers/objectWithoutProperties' => ['version' => '7.28.4'],
    'htm' => ['version' => '3.1.1'],
    '@stimulus-components/dialog' => ['version' => '1.0.1'],
    'pretty-print-json' => ['version' => '3.0.8'],
    'pretty-print-json/dist/css/pretty-print-json.min.css' => ['version' => '3.0.8', 'type' => 'css'],
    '@andypf/json-viewer' => ['version' => '2.8.0'],
    'loglevel' => ['version' => '1.9.2'],
    'loglevel-plugin-prefix' => ['version' => '0.8.4'],
    'debug' => ['version' => '4.4.3'],
    'ms' => ['version' => '2.1.3'],
    '@babel/runtime/helpers/typeof' => ['version' => '7.28.4'],
    '@babel/runtime/helpers/slicedToArray' => ['version' => '7.28.4'],
    '@babel/runtime/helpers/toConsumableArray' => ['version' => '7.28.4'],
    'chordsheetjs' => ['version' => '13.0.0'],
    'jspdf' => ['version' => '3.0.4'],
    'fflate' => ['version' => '0.8.2'],
    'fast-png' => ['version' => '6.4.0'],
    'iobuffer' => ['version' => '5.4.0'],
    'pako' => ['version' => '2.1.0'],
    'datatables.net-columncontrol-bs5' => ['version' => '2.1.2'],
    'datatables.net-columncontrol' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.css' => ['version' => '2.1.2', 'type' => 'css'],
    '@tacman1123/twig-browser' => ['version' => '1.0.0'],
    '@tacman1123/twig-browser/src/compat/compileTwigBlocks.js' => ['version' => '1.0.0'],
    '@tacman1123/twig-browser/adapters/symfony' => ['version' => '1.0.0'],
    'dexie' => ['version' => '4.3.0'],
    'marked' => ['version' => '18.0.9'],
    '@swc/helpers/esm/_sliced_to_array.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_to_consumable_array.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_define_property.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_extends.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_destructuring_empty.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_spread.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_spread_props.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_type_of.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_instanceof.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_without_properties.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_call_super.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_class_call_check.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_create_class.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_inherits.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_wrap_native_super.js' => ['version' => '0.5.18'],
    'side-channel' => ['version' => '1.1.1'],
    'es-errors/type' => ['version' => '1.3.0'],
    'object-inspect' => ['version' => '1.13.4'],
    'side-channel-list' => ['version' => '1.0.1'],
    'side-channel-map' => ['version' => '1.0.1'],
    'side-channel-weakmap' => ['version' => '1.0.2'],
    'get-intrinsic' => ['version' => '1.2.5'],
    'call-bound' => ['version' => '1.0.2'],
    'es-errors' => ['version' => '1.3.0'],
    'es-errors/eval' => ['version' => '1.3.0'],
    'es-errors/range' => ['version' => '1.3.0'],
    'es-errors/ref' => ['version' => '1.3.0'],
    'es-errors/syntax' => ['version' => '1.3.0'],
    'es-errors/uri' => ['version' => '1.3.0'],
    'gopd' => ['version' => '1.2.0'],
    'es-define-property' => ['version' => '1.0.1'],
    'has-symbols' => ['version' => '1.1.0'],
    'dunder-proto/get' => ['version' => '1.0.0'],
    'call-bind-apply-helpers/functionApply' => ['version' => '1.0.0'],
    'call-bind-apply-helpers/functionCall' => ['version' => '1.0.0'],
    'function-bind' => ['version' => '1.1.2'],
    'hasown' => ['version' => '2.0.2'],
    'call-bind' => ['version' => '1.0.8'],
    'call-bind-apply-helpers' => ['version' => '1.0.0'],
    'set-function-length' => ['version' => '1.2.2'],
    'call-bind-apply-helpers/applyBind' => ['version' => '1.0.0'],
    'define-data-property' => ['version' => '1.1.4'],
    'has-property-descriptors' => ['version' => '1.0.2'],
    'markdown-to-jsx' => ['version' => '7.7.17'],
    'react' => ['version' => '19.2.0'],
    'markdown-to-jsx/entities' => ['version' => '9.8.2'],
    'bootstrap' => ['version' => '5.3.8'],
    'chart.js' => ['version' => '4.5.1'],
    '@tabler/core' => ['version' => '1.6.1'],
    'algoliasearch-helper' => ['version' => '3.29.3'],
    'qs' => ['version' => '6.15.3'],
    'preact' => ['version' => '10.29.8'],
    'chart.js/auto' => ['version' => '4.5.1'],
    'algoliasearch-helper/types/algoliasearch.js' => ['version' => '3.29.3'],
    'preact/hooks' => ['version' => '10.29.8'],
    'instantsearch.js' => ['version' => '4.110.0'],
    'instantsearch.js/es/widgets' => ['version' => '4.110.0'],
    'instantsearch-ui-components' => ['version' => '0.34.0'],
    '@meilisearch/instant-meilisearch' => ['version' => '0.31.3'],
    'meilisearch' => ['version' => '0.60.0'],
    'instantsearch.css/themes/algolia.min.css' => ['version' => '8.19.0', 'type' => 'css'],
    'stimulus-attributes' => ['version' => '1.0.2'],
    'datatables.net-bs5/css/dataTables.bootstrap5.min.css' => ['version' => '3.1.3', 'type' => 'css'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-scroller-bs5/css/scroller.bootstrap5.min.css' => ['version' => '3.0.0', 'type' => 'css'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-select-bs5/css/select.bootstrap5.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    '@floating-ui/dom' => ['version' => '1.8.0'],
    '@floating-ui/core' => ['version' => '1.8.0'],
    '@floating-ui/utils' => ['version' => '0.2.12'],
    '@floating-ui/utils/dom' => ['version' => '0.2.12'],
    '@symfony/ux-live-component' => ['path' => './vendor/symfony/ux-live-component/assets/dist/live_controller.js'],
    'datatables.net-fixedcolumns' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs5' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedheader' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs5' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-rowgroup' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs5' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs5/css/rowGroup.bootstrap5.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-bs5/css/rowGroup.bootstrap5.css' => ['version' => '2.1.1', 'type' => 'css'],
    'd3-graphviz' => ['version' => '5.6.0'],
    'd3-selection' => ['version' => '3.0.0'],
    'd3-dispatch' => ['version' => '3.0.1'],
    'd3-transition' => ['version' => '3.0.1'],
    'd3-timer' => ['version' => '3.0.1'],
    'd3-interpolate' => ['version' => '3.0.1'],
    'd3-zoom' => ['version' => '3.0.0'],
    '@hpcc-js/wasm/graphviz' => ['version' => '2.20.0'],
    'd3-format' => ['version' => '3.1.0'],
    'd3-path' => ['version' => '3.1.0'],
    'd3-color' => ['version' => '3.0.1'],
    'd3-ease' => ['version' => '3.0.1'],
    'd3-drag' => ['version' => '3.0.0'],
];
